[[constraint]]
  name = "github.com/NebulousLabs/hdkey"
  revision = "aee6f80cd15d714ed7bffbb947b61ff563760859"

[[constraint]]
  name = "github.com/btcsuite/btcd"
  revision = "2a560b2036bee5e3679ec2133eb6520b2f195213"

[[constraint]]
  name = "github.com/roasbeef/go-go-gadget-paillier"
  revision = "14f1f86b60008ece97b6233ed246373e555fc79f"

[prune]
  go-tests = true
  unused-packages = true
